esphome:
  name: "esphome-emerson"
  friendly_name: Emerson_Vertiv_R48

esp32:
  board: node32s
  framework:
    type: esp-idf

external_components:
  - source: github://leodesigner/esphome-emerson-vertiv-r48
    refresh: 0s

logger:
  level: INFO
  logs:
    canbus: WARN
    emerson_r48: INFO

api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Esphome-Emerson"
    password: "qwertyzxc"

ota:
 - platform: esphome
   password: "ota_password"

captive_portal:

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt
  password: !secret mqtt_pass
  client_id: emerson_r48_3000e3
  id: mqtt_client
  topic_prefix: eh/emerson
  discovery: true                 
  discovery_prefix: homeassistant 
  discovery_retain: true          
  keepalive: 60s                  
  reboot_timeout: 0s              
  birth_message:
    topic: eh/emerson/status
    payload: online
    retain: true
  will_message:
    topic: eh/emerson/status
    payload: offline
    retain: true

spi:
  - id: McpSpi
    clk_pin: GPIO18
    mosi_pin: GPIO23
    miso_pin: GPIO19

canbus:
  - platform: mcp2515
    id: can
    spi_id: McpSpi
    use_extended_id: true
    cs_pin: GPIO5
    can_id: 0x0607FF83
    bit_rate: 125kbps
    mode: NORMAL

emerson_r48:
  canbus_id: can
  update_interval: 5s

sensor:
  - platform: emerson_r48
    output_voltage:
      name: Output voltage
    output_current:
      name: Output current
    output_temp:
      name: Temperature
    input_voltage:
      name: AC Voltage
    max_output_current:
      name: DC max current

number:
  - platform: emerson_r48
    output_voltage:
      name: Set output voltage
    max_output_current:
      name: Max output current
    max_input_current:
      name: Max input current

button:
  - platform: emerson_r48
    set_offline_values:
      name: Set offline values
  - platform: restart
    name: "Restart ESP"

switch:
  - platform: emerson_r48
    ac_sw:
      name: "AC switch Turn OFF"
    dc_sw:
      name: "DC switch Turn OFF"
    fan_sw:
      name: "FAN switch MAX"
    led_sw:
      name: "LED switch"
